services:
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: telegram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 2344:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
        
  telegram-bot:
    build:
      context: ./
      dockerfile: ./Program/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on: 
      db:
        condition: service_healthy

volumes: 
  db-data:
    
